import nodemailer from "nodemailer";
import path from "node:path";

/**
 * Dispatches automated transactional receipts with custom PDF file attachments
 * @param {Object} data - The complete structured tradeData object tracking parameters
 * @param {string} pdfFilename - The exact filename string generated by your PDF engine
 */
export async function generateEmail(data, pdfFilename) {
  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: "your@gmail.com", // Replace with your standard distribution email address
      pass: process.env.EMAIL_PASS, // Your secured 16-character Google App Password
    },
  });

  // Construct the absolute path tracking where the PDF sits on Render's hard drive
  const absolutePdfPath = path.join(process.cwd(), pdfFilename);

  await transporter.sendMail({
    from: '"Global Trade Desk" <your@gmail.com>',
    to: data.customer.email,
    subject: `🚨 Trade Confirmation: Asset Allocation Verified (${data.commodity})`,
    text: `Hello ${data.customer.fullName},\n\nYour purchase order has been executed successfully.\n\nAsset: ${data.commodity}\nStrike Rate: $${data.price.toFixed(2)}\nInvested Principal: ${data.currency} ${data.amount.toFixed(2)}\n\nPlease find your official transaction contract PDF receipt attached to this message.\n\nBest Regards,\nGlobal Trade Risk Compliance Desk`,
    attachments: [
      {
        filename: pdfFilename,
        path: absolutePdfPath, // Nodemailer reads this path dynamically and attaches the file
      },
    ],
  });

  console.log(
    `📧 Transaction confirmation email with attachment ${pdfFilename} dispatched successfully.`,
  );
}
